name: my first workflow

on:
  push:
    branches:
      - testpipeline

jobs: 
  first_job:
    runs-on: [ubuntu-latest, windows]
    steps:
    - name: welcome message
      run: echo "my first github action job"

    - name: List files
      run: ls
    
    - name: Read files
      run: cat D:\mini-python-project\python-mini-project\Diff_Utility\README.md




