name: 🚀 Pipeline CI/CD Principal

on:
  # Permet le déclenchement par le scheduler (via l'API)
  workflow_dispatch:
    inputs:
      source:
        description: 'Source de déclenchement (scheduled_run ou manuel)'
        required: true
        default: 'manuel'

jobs:
  # Votre pipeline commence ici
  build_and_deploy:
    runs-on: ubuntu-latest
    
    # Condition : Vérifie si le déclenchement vient bien de la branche develop
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout du code (sur la branche develop spécifiée)
        uses: actions/checkout@v4
        
      - name: Afficher la source de déclenchement
        run: echo "Déclenché par : ${{ github.event.inputs.source }}"
      
      # Ajoutez ici le reste de vos étapes (build, test, deploy, etc.)
      # ...
