name: ⏰ Planificateur Quotidien

on:
  schedule:
    # Déclenchement à 7h30 du matin (Heure UTC)
    - cron: '30 7 * * *'
    # Déclenchement à 15h30 (Heure UTC)
    - cron: '30 15 * * *'

jobs:
  trigger_build:
    runs-on: ubuntu-latest
    steps:
      - name: Déclencher le pipeline principal sur develop
        uses: actions/github-script@v6
        with:
          script: |
            // Cette commande utilise l'API GitHub pour déclencher le second workflow
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'main.yml', // Le nom du fichier de votre workflow principal
              ref: 'develop',           // La branche sur laquelle le pipeline doit travailler
              // Vous pouvez passer des inputs si nécessaire ici
              inputs: {
                source: 'scheduled_run'
              }
            });
